spring:
  application:
    name: springboot
  datasource:
    username: postgres
    password: '&B&8hr'
    url: jdbc:postgresql://localhost/reserva-de-voos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
